version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - project_mariadb:/var/lib/mysql
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    ports:
      - 9200:80

volumes:
  project_mariadb:
